service: alaqari-app-auth

provider:
  name: aws
  stage: dev
  region: eu-west-1

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

resources:
  - ${file(./resources/cognito-user-pool.yml):Resources}
  - ${file(./resources/cognito-identity-pool.yml):Resources}

# Print out the Id of the User Pool and Identity Pool that are created
Outputs:
  UserPoolId:
    Value:
      Ref: CognitoUserPool

  UserPoolClientId:
    Value:
      Ref: CognitoUserPoolClient

  IdentityPoolId:
    Value:
      Ref: CognitoIdentityPool

  CognitoAuthRole:
    Value:
      Ref: CognitoAuthRole
    Export:
      Name: CognitoAuthRole-${self:custom.stage}
