service: alaqari-app-uploads

provider:
  name: aws
  stage: dev
  region: eu-west-1

custom:
  # Our stage is based on what is passed in when running serverless
  # commands. Or fallsback to what we have set in the provider section.
  stage: ${opt:stage, self:provider.stage}

resources:
  - ${file('./resources/s3-bucket-uploads.yml'):Resources}

# Print out the name of the bucket that is created
Outputs:
  UploadsBucketArn:
    Value:
        Fn::GetAtt:
        - UploadsBucket
        - Arn
    Export:
      Name: ${self:custom.stage}-UploadsBucketArn

  UploadsBucketName:
    Value:
      Ref: UploadsBucket
    Export:
      Name: ${self:custom.stage}-UploadsBucketName
